### ISSUE TITLE
회원가입 - 구현

### ISSUE THREAD

**Issue by kitaee** [kitaee/wanted-pre-onboarding-backend#1]
### 📃 Description
사용자 회원가입 엔드포인트 관련

### ✔ Todo
- [x] 이메일 조건 : @ 포함
- [x] 비밀번호 조건 : 8자 이상
- [x] 비밀번호는 반드시 암호화
- [x] 부가 유효성 X
- [x] 이메일과 비밀번호로 회원가입 가능한 로직

### 🔴 ETC
예상 개발 기간: 2시간
