### ISSUE TITLE
회원가입 - 테스트

### ISSUE THREAD

**Issue by kitaee** [kitaee/wanted-pre-onboarding-backend#2]
### 📃 Description
사용자 회원가입 테스트 관련

### ✔ Todo
- [x] 이메일 중복 테스트 (실패)
- [x] 이메일 중복 테스트 (성공)
- [x] 이메일 조건 테스트 (실패)
- [x] 이메일 조건 테스트 (성공)
- [x] 비밀번호 조건 테스트 (실패)
- [x] 비밀번호 조건 테스트 (성공)

### 🔴 ETC
예상 개발 기간: 1시간 30분
